# Auto-generated by IDE. All changes by user will be lost!
# Created at 1/22/13 7:32 AM

BASEDIR = $$_PRO_FILE_PWD_

INCLUDEPATH +=  \
    $$BASEDIR/src

SOURCES +=  \
    $$BASEDIR/src/BookFilterModel.cpp \
    $$BASEDIR/src/cascadestester.cpp \
    $$BASEDIR/src/FilterProxyDataModel.cpp \
    $$BASEDIR/src/filterproxydatamodeltest.cpp \
    $$BASEDIR/src/main.cpp

HEADERS +=  \
    $$BASEDIR/src/BookFilterModel.hpp \
    $$BASEDIR/src/cascadestester.hpp \
    $$BASEDIR/src/FilterProxyDataModel.hpp \
    $$BASEDIR/src/FilterProxyDataModel_p.hpp \
    $$BASEDIR/src/filterproxydatamodeltest.hpp

CONFIG += precompile_header
PRECOMPILED_HEADER = $$BASEDIR/precompiled.h

lupdate_inclusion {
    SOURCES += \
        $$BASEDIR/../assets/*.qml
}

TRANSLATIONS = \
    $${TARGET}.ts

